[package]
name = "frontend"
version = "0.1.0"
authors = ["spriest487 <spriest487@googlemail.com>"]
edition = "2021"

[dependencies]
common = { path = "../common" }
ir-lang = { path = "../ir_lang" }
bigdecimal = "0.4.5"
cast = "0.3.0"
derivative = "2.2.0"
linked-hash-map = "0.5.6"
regex = "1.10.6"
